@echo off
echo Starting PostgreSQL database container...
docker-compose up -d pragma_pg
echo Waiting for database to be ready...
timeout /t 5 /nobreak
echo Generating Alembic migrations...
docker-compose run --rm backend alembic revision --autogenerate -m "Initial schema"
echo Applying migrations...
docker-compose run --rm backend alembic upgrade head
echo Done!
