import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowRight, CheckCircle2, Sparkles, X, Check, Loader2, Maximize2, TrendingUp, ShieldAlert } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useToast } from '../../contexts/ToastContext';
import api from '../../services/api';

interface Policy {
  id: number;
  title: string;
  savings: string;
  impact: 'Critical' | 'High' | 'Medium';
  confidence: number;
  reason: string;
  applied?: boolean;
  category: string;
  timeline: string;
  governanceBoost: string;
}

const initialPolicies: Policy[] = [
  { 
    id: 1, 
    title: 'Increase healthcare budget by 12%', 
    savings: '₹4.5 Cr', 
    impact: 'High', 
    confidence: 94, 
    reason: 'Predictive models show a 30% spike in hospital admissions due to upcoming monsoon season.',
    category: 'Healthcare Infrastructure',
    timeline: 'Immediate (1-3 Days)',
    governanceBoost: '+4.2%'
  },
  { 
    id: 2, 
    title: 'Deploy 20 additional emergency response units', 
    savings: '₹1.2 Cr', 
    impact: 'Medium', 
    confidence: 88, 
    reason: 'Average response time in Sector 4 has degraded by 4 minutes.',
    category: 'Public Safety',
    timeline: '24 Hours',
    governanceBoost: '+2.8%'
  },
  { 
    id: 3, 
    title: 'Allocate ₹2.3 Cr for urban flood mitigation', 
    savings: '₹15.0 Cr', 
    impact: 'Critical', 
    confidence: 97, 
    reason: 'Simulations indicate 85% probability of severe flooding in low-lying zones next week.',
    category: 'Disaster Prevention',
    timeline: 'Immediate (Within 12 Hours)',
    governanceBoost: '+8.5%'
  },
];

export default function PolicyRecommendations() {
  const [policies, setPolicies] = useState<Policy[]>(initialPolicies);
  const [selectedPolicy, setSelectedPolicy] = useState<Policy | null>(null);
  const [applyingId, setApplyingId] = useState<number | null>(null);
  const navigate = useNavigate();
  const { addToast } = useToast();

  const handleApplyPolicy = async (e: React.MouseEvent, policy: Policy) => {
    e.stopPropagation();
    if (policy.applied || applyingId === policy.id) return;

    setApplyingId(policy.id);

    try {
      await api.post('/policies/apply', { policy_id: policy.id, title: policy.title });
    } catch (err) {
      // Fallback response for offline API
    }

    setTimeout(() => {
      setPolicies(prev => prev.map(p => p.id === policy.id ? { ...p, applied: true } : p));
      setApplyingId(null);
      if (selectedPolicy?.id === policy.id) {
        setSelectedPolicy(prev => prev ? { ...prev, applied: true } : null);
      }
      addToast(`Policy Applied: "${policy.title}" (${policy.savings} saved)`, 'success');
    }, 800);
  };

  return (
    <>
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.2 }}
        className="glass-card h-[380px] flex flex-col justify-between"
      >
        <div>
          <div className="flex justify-between items-start mb-3">
            <div>
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary animate-pulse" />
                <h3 className="text-white font-poppins font-medium">AI Policy Recommendations</h3>
              </div>
              <p className="text-[10px] text-gray-500 uppercase tracking-wider">Generated by LLM Swarm Coordinator</p>
            </div>
            <button 
              onClick={() => navigate('/policies')}
              className="text-[10px] uppercase font-bold text-primary hover:text-white flex items-center gap-1 transition-colors bg-primary/10 hover:bg-primary/20 px-2 py-1 rounded"
            >
              View All <Maximize2 className="w-2.5 h-2.5" />
            </button>
          </div>
          
          <div className="overflow-y-auto custom-scrollbar pr-1 space-y-3 max-h-[280px]">
            {policies.map((policy, i) => (
              <motion.div 
                key={policy.id}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.15 }}
                onClick={() => setSelectedPolicy(policy)}
                className={`p-3.5 rounded-xl border transition-all duration-200 cursor-pointer relative overflow-hidden group ${
                  policy.applied 
                    ? 'bg-success/5 border-success/30 hover:bg-success/10' 
                    : 'bg-white/5 border-white/10 hover:border-primary/50 hover:bg-white/10'
                }`}
              >
                <div className={`absolute left-0 top-0 bottom-0 w-1 ${
                  policy.applied
                    ? 'bg-success'
                    : policy.impact === 'Critical' ? 'bg-danger' : policy.impact === 'High' ? 'bg-warning' : 'bg-primary'
                }`}></div>
                
                <div className="flex justify-between items-start mb-1.5 pl-2">
                  <h4 className="text-xs font-semibold text-white max-w-[70%] group-hover:text-primary transition-colors flex items-center gap-1.5">
                    {policy.title}
                  </h4>
                  <div className="text-right">
                    <span className="text-[11px] font-bold text-success">{policy.confidence}% Conf.</span>
                    <div className="text-[9px] text-gray-400">Impact: {policy.impact}</div>
                  </div>
                </div>
                
                <p className="text-[11px] text-gray-400 mb-2 pl-2 line-clamp-2">{policy.reason}</p>
                
                <div className="flex justify-between items-center pl-2 pt-1 border-t border-white/5">
                  <div className="text-[11px] text-secondary font-mono">Est. Savings: {policy.savings}</div>
                  
                  <button 
                    onClick={(e) => handleApplyPolicy(e, policy)}
                    disabled={policy.applied || applyingId === policy.id}
                    className={`text-[10px] uppercase tracking-wider font-bold px-2.5 py-1 rounded flex items-center gap-1.5 transition-all ${
                      policy.applied
                        ? 'bg-success/20 text-success border border-success/40'
                        : 'bg-primary/20 text-primary hover:bg-primary hover:text-white border border-primary/40'
                    }`}
                  >
                    {applyingId === policy.id ? (
                      <>
                        <Loader2 className="w-3 h-3 animate-spin" /> Applying...
                      </>
                    ) : policy.applied ? (
                      <>
                        <CheckCircle2 className="w-3 h-3" /> Applied
                      </>
                    ) : (
                      <>
                        Apply Action <ArrowRight className="w-3 h-3" />
                      </>
                    )}
                  </button>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </motion.div>

      {/* POLICY DETAILS MODAL */}
      <AnimatePresence>
        {selectedPolicy && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-md">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="glass-card max-w-lg w-full p-6 bg-[#111827] border border-white/20 shadow-2xl rounded-2xl relative overflow-hidden"
            >
              <button 
                onClick={() => setSelectedPolicy(null)}
                className="absolute top-4 right-4 text-gray-400 hover:text-white p-1 rounded-full bg-white/5 hover:bg-white/10"
              >
                <X className="w-5 h-5" />
              </button>

              <div className="flex items-center gap-2 text-xs font-mono text-primary font-semibold uppercase tracking-wider mb-2">
                <Sparkles className="w-4 h-4" /> Policy Detail & AI Reasoning
              </div>

              <h3 className="text-lg font-bold text-white mb-2">{selectedPolicy.title}</h3>

              <div className="flex gap-2 mb-4">
                <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-primary/20 text-primary border border-primary/30">
                  {selectedPolicy.category}
                </span>
                <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded ${
                  selectedPolicy.impact === 'Critical' ? 'bg-danger/20 text-danger border border-danger/30' : 'bg-warning/20 text-warning border border-warning/30'
                }`}>
                  {selectedPolicy.impact} Priority
                </span>
                <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-success/20 text-success border border-success/30">
                  {selectedPolicy.confidence}% AI Confidence
                </span>
              </div>

              <div className="space-y-3 mb-6 bg-white/5 p-4 rounded-xl border border-white/5">
                <div>
                  <div className="text-[10px] uppercase text-gray-500 font-semibold mb-1">AI Swarm Rationale</div>
                  <p className="text-xs text-gray-200 leading-relaxed">{selectedPolicy.reason}</p>
                </div>

                <div className="grid grid-cols-3 gap-2 pt-2 border-t border-white/10">
                  <div>
                    <div className="text-[9px] text-gray-400 uppercase">Est. Cost Saved</div>
                    <div className="text-xs font-mono font-bold text-success">{selectedPolicy.savings}</div>
                  </div>
                  <div>
                    <div className="text-[9px] text-gray-400 uppercase">Governance Score</div>
                    <div className="text-xs font-mono font-bold text-primary flex items-center gap-0.5">
                      <TrendingUp className="w-3 h-3" /> {selectedPolicy.governanceBoost}
                    </div>
                  </div>
                  <div>
                    <div className="text-[9px] text-gray-400 uppercase">Implementation</div>
                    <div className="text-xs font-mono font-bold text-gray-200">{selectedPolicy.timeline}</div>
                  </div>
                </div>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={() => {
                    setSelectedPolicy(null);
                    navigate('/policies');
                  }}
                  className="flex-1 text-xs font-semibold py-2.5 px-4 rounded-xl border border-white/10 hover:border-white/30 text-gray-300 hover:text-white transition-colors"
                >
                  Open Sandbox
                </button>
                <button
                  onClick={(e) => {
                    handleApplyPolicy(e, selectedPolicy);
                  }}
                  disabled={selectedPolicy.applied || applyingId === selectedPolicy.id}
                  className={`flex-1 text-xs font-bold py-2.5 px-4 rounded-xl flex items-center justify-center gap-2 transition-all ${
                    selectedPolicy.applied
                      ? 'bg-success/20 text-success border border-success/40'
                      : 'bg-primary text-white hover:bg-primary/90 shadow-[0_0_15px_rgba(37,99,235,0.4)]'
                  }`}
                >
                  {applyingId === selectedPolicy.id ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" /> Processing...
                    </>
                  ) : selectedPolicy.applied ? (
                    <>
                      <Check className="w-4 h-4" /> Intervention Applied
                    </>
                  ) : (
                    <>
                      Execute Intervention
                    </>
                  )}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}
